In [1]:
# Import the necessary libraries

import numpy as np

Indexing & Slicing Operations of 1 Dimensional Array

In [2]:
arr1 = np.array([0,1,2,3,4,5])
print(arr1[5])
print(arr1[2:4])

5
[2 3]


Propagation & Broadcast

In [3]:
arr1 = np.array([0,1,2,3,4,5])
arr1[2:4] = -1
print(arr1)

arr1[2:4] = [-2,-2]
print(arr1)

[ 0  1 -1 -1  4  5]
[ 0  1 -2 -2  4  5]


Array slices are the views of the original array. So, any change to the np array will also effect the original np array

In [4]:
arr1 = np.array([0,1,2,3,4,5])
arr1_sub = arr1[2:4]
arr1_sub[:] = -3
print(arr1)

[ 0  1 -3 -3  4  5]


Indexing & Slicing for a 2 Dimensional Array

In [ ]:
arr1 = np.array([[0,1,2,3,4,5,6],[10,11,12,13,14,15,16],[20,21,22,23,24,25,26],[30,31,32,33,34,35,36]])
print(arr1[3,4])
print(arr1[:,4])
print(arr1[1][3])

Indexing & Slicing for a 3 Dimensional Array

In [ ]:
arr1 = np.array([[[0,1,2,3,4,5,6],[10,11,12,13,14,15,16],[20,21,22,23,24,25,26],[30,31,32,33,34,35,36]],
[[100,101,102,103,104,105,106],[110,111,112,113,114,115,116],[120,121,122,123,124,125,126],[130,131,132,133,134,135,136]]])

#[Depth][Row][Column]
print(arr1[1][3][1])
print(arr1[0][2][4])
print(arr1[:,1,:])
print(arr1[:][0][2])

# Assign values to a array
arr1[0] = 99
# print(arr1)

arr1[:,2:4,3]

Indexing and Slicing using Filters

In [5]:
arr1 = np.array([[0,1,2,3,4,5,6],[10,11,12,13,14,15,16],[20,21,22,23,24,25,26],[30,31,32,33,34,35,36]])
X_Filter = np.array([True,False,True,False])
print(X_Filter==True)
print(arr1[X_Filter == True,:])

Y_Filter = np.array([True,False,True,False,True,False,True])
print(arr1[:,Y_Filter==True])

# print(arr1[X_Filter==True,Y_Filter==True]) - Understand why is this erroring out

[ True False  True False]
[[ 0  1  2  3  4  5  6]
 [20 21 22 23 24 25 26]]
[[ 0  2  4  6]
 [10 12 14 16]
 [20 22 24 26]
 [30 32 34 36]]


In [ ]:
arr1 = np.array([[0,1,2,3,4,5,6],[10,11,12,13,14,15,16],[20,21,22,23,24,25,26],[30,31,32,33,34,35,36]])

print(arr1[arr1<13])

arr1[arr1<13] = 0
print(arr1)

Fancy Indexing

In [10]:
arr1 = np.array([[0,1,2,3,4,5,6],[10,11,12,13,14,15,16],[20,21,22,23,24,25,26],[30,31,32,33,34,35,36]])

# Provide the list of rows or columns for indexing
print(arr1[[1,2,3],[0]])
print(arr1[[0,1,3],[1,3,4]])

# Provide the output of one indexing as input to the next
print(arr1[[1,3]][:,[0,1,3,5]][0,:])

[10 20 30]
[ 1 13 34]
[10 11 13 15]


Transpose Array

In [11]:
arr1 = np.arange(32).reshape(4,8)
print(arr1)

arrT = arr1.transpose()
print(arrT)


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
[[ 0  8 16 24]
 [ 1  9 17 25]
 [ 2 10 18 26]
 [ 3 11 19 27]
 [ 4 12 20 28]
 [ 5 13 21 29]
 [ 6 14 22 30]
 [ 7 15 23 31]]
